change texts and sharesData replaces shares
bloxapp/ssv-keys pull request #42
Opened 2023-06-11 09:26 UTC by vadiminc

Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

2023-06-11 09:41 UTC, yoanatanblox requested changes

2023-06-11 09:41 UTC, yoanatanblox commented on src/commands/actions/arguments/owner-nonce.ts
> +    help: 'The validator registration nonce of the account (owner address) within the SSV contract (increments after each validator registration), obtained using the ssv-scanner tool.'
"The validator owner nonce of the account (owner address) within the SSV contract (increments after each validator registration), obtained using the ssv-scanner tool."

2023-06-11 09:41 UTC, yoanatanblox commented on src/commands/actions/arguments/owner-nonce.ts
> +      message: 'Please provide a validator registration nonce of the account (owner address)',
"Please provide a valid owner nonce of the account (owner address) obtained using the ssv-scanner tool.

2023-06-11 11:17 UTC, axelrod-blox approved these changes

2023-06-12 09:45 UTC, andrew-blox approved these changes

2023-06-13 09:09 UTC, axelrod-blox approved these changes

2023-06-13 09:14 UTC, meshin-dev approved these changes

2023-06-13 09:21 UTC, merged