Bulk Keys support in ssv-keys
bloxapp/ssv-keys pull request #47
Opened 2023-07-24 16:29 UTC by vadiminc

Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

2023-07-25 08:11 UTC, axelrod-blox commented on src/cli-shared.ts
> +
unnecessary space

2023-07-25 08:14 UTC, axelrod-blox commented on src/commands/actions/KeySharesAction.ts
empty field

2023-07-25 08:18 UTC, axelrod-blox commented on src/commands/actions/arguments/password.ts
> +// import { keystorePasswordValidator } from '../validators/keystore-password';
If we doesn't need it let's remove

2023-07-25 08:19 UTC, axelrod-blox approved these changes

2023-07-25 08:33 UTC, meshin-dev requested changes
@vadiminc
1. Jon have refactored PRD, we should listen to him and revise what's done
2. I think this solution is over-complicated and we should take a closer look of how to use advantages of architecture and try to not change deeper levels of the code if not necessary

2023-07-27 10:33 UTC, meshin-dev approved these changes

2023-07-27 10:33 UTC, meshin-dev commented on src/cli-shared.ts
> +    outputFiles.map((file: string) => console.debug(`${colors.bgYellow(colors.black(file))}`));
Use forEach instead of map)

2023-07-27 13:53 UTC, andrew-blox approved these changes

2023-07-27 14:11 UTC, merged